export const countriesMap: Record<string, string> = {
  AD: "Andorra",
  AE: "Emirados Árabes Unidos",
  AF: "Afeganistão",
  AG: "Antígua e Barbuda",
  AL: "Albânia",
  AM: "Armênia",
  AO: "Angola",
  AR: "Argentina",
  AT: "Áustria",
  AU: "Austrália",
  AZ: "Azerbaijão",
  BA: "Bósnia e Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Bélgica",
  BF: "Burkina Faso",
  BG: "Bulgária",
  BH: "Bahrein",
  BI: "Burundi",
  BJ: "Benim",
  BN: "Brunei",
  BO: "Bolívia",
  BR: "Brasil",
  BS: "Bahamas",
  BT: "Butão",
  BW: "Botsuana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canadá",
  CD: "Congo-Kinshasa",
  CF: "República Centro-Africana",
  CG: "Congo-Brazzaville",
  CH: "Suíça",
  CI: "Costa do Marfim",
  CL: "Chile",
  CM: "Camarões",
  CN: "China",
  CO: "Colômbia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cabo Verde",
  CY: "Chipre",
  CZ: "Tcheca",
  DE: "Alemanha",
  DJ: "Djibuti",
  DK: "Dinamarca",
  DO: "República Dominicana",
  DZ: "Argélia",
  EC: "Equador",
  EE: "Estônia",
  EG: "Egito",
  ES: "Espanha",
  ET: "Etiópia",
  FI: "Finlândia",
  FJ: "Fiji",
  FR: "França",
  GA: "Gabão",
  GB: "Reino Unido",
  GD: "Granada",
  GE: "Geórgia",
  GH: "Gana",
  GM: "Gâmbia",
  GN: "Guiné",
  GQ: "Guiné Equatorial",
  GR: "Grécia",
  GT: "Guatemala",
  GW: "Guiné-Bissau",
  GY: "Guiana",
  HK: "Hong Kong",
  HN: "Honduras",
  HR: "Croácia",
  HT: "Haiti",
  HU: "Hungria",
  ID: "Indonésia",
  IE: "Irlanda",
  IL: "Israel",
  IN: "Índia",
  IQ: "Iraque",
  IR: "Irã",
  IS: "Islândia",
  IT: "Itália",
  JM: "Jamaica",
  JO: "Jordânia",
  JP: "Japão",
  KE: "Quênia",
  KG: "Quirguistão",
  KH: "Camboja",
  KP: "Coreia do Norte",
  KR: "Coreia do Sul",
  KW: "Kuwait",
  KZ: "Cazaquistão",
  LA: "Laos",
  LB: "Líbano",
  LC: "Santa Lúcia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Libéria",
  LS: "Lesoto",
  LT: "Lituânia",
  LU: "Luxemburgo",
  LV: "Letônia",
  LY: "Líbia",
  MA: "Marrocos",
  MC: "Mônaco",
  MD: "Moldávia",
  ME: "Montenegro",
  MG: "Madagascar",
  MK: "Macedônia do Norte",
  ML: "Mali",
  MM: "Mianmar",
  MN: "Mongólia",
  MO: "Macau",
  MR: "Mauritânia",
  MT: "Malta",
  MU: "Maurício",
  MV: "Maldivas",
  MW: "Malawi",
  MX: "México",
  MY: "Malásia",
  MZ: "Moçambique",
  NA: "Namíbia",
  NE: "Níger",
  NG: "Nigéria",
  NI: "Nicarágua",
  NL: "Países Baixos",
  NO: "Noruega",
  NP: "Nepal",
  NZ: "Nova Zelândia",
  OM: "Omã",
  PA: "Panamá",
  PE: "Peru",
  PH: "Filipinas",
  PK: "Paquistão",
  PL: "Polônia",
  PT: "Portugal",
  PY: "Paraguai",
  QA: "Catar",
  RO: "Romênia",
  RS: "Sérvia",
  RU: "Rússia",
  RW: "Ruanda",
  SA: "Arábia Saudita",
  SE: "Suécia",
  SG: "Singapura",
  SI: "Eslovênia",
  SK: "Eslováquia",
  SL: "Serra Leoa",
  SN: "Senegal",
  SO: "Somália",
  SR: "Suriname",
  ST: "São Tomé e Príncipe",
  SV: "El Salvador",
  SY: "Síria",
  SZ: "Eswatini",
  TD: "Chade",
  TG: "Togo",
  TH: "Tailândia",
  TJ: "Tajiquistão",
  TL: "Timor-Leste",
  TM: "Turcomenistão",
  TN: "Tunísia",
  TR: "Turquia",
  TT: "Trinidad e Tobago",
  TW: "Taiwan",
  TZ: "Tanzânia",
  UA: "Ucrânia",
  UG: "Uganda",
  US: "Estados Unidos",
  UY: "Uruguai",
  UZ: "Uzbequistão",
  VC: "São Vicente e Granadinas",
  VE: "Venezuela",
  VN: "Vietnã",
  ZA: "África do Sul",
  ZM: "Zâmbia",
  ZW: "Zimbábue",
  unknown: "Desconhecido",
} as const;
